# Generated by Django 3.0.5 on 2020-04-24 14:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200423_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='decription',
            field=models.TextField(blank=True, verbose_name='Recipe Description'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to=api.models.recipe_image_file_path, verbose_name='Image'),
        ),
    ]
